name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master

jobs:
  install-test-build-push:
    runs-on: ubuntu-latest
    container: biomapas/cicd-full:0.0.2

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pip install . --upgrade
          pip list

      - name: SetupCDK
        run: |
          npm remove -g aws-cdk
          npm install -g aws-cdk

      - name: UnitTest
        run: pytest --cov=b_lambda_layer_common b_lambda_layer_common_test/unit --cov-fail-under=80

      - name: IntegrationTest
        run: pytest b_lambda_layer_common_test/integration/tests

      - name: Install
        run: pip install wheel twine

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Upload
        run: twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
